blank_issues_enabled: false
contact_links:
  - name: Support Documentation
    url: https://github.com/vrrajsri/CarnaticMetronome-Support/blob/main/SUPPORT.md
    about: Check our support documentation for FAQs and troubleshooting

